#pragma once

#include <array>
#include <string>

const int POSSIBLE_WORDS_NUMBER{ 47 };
const std::array< std::string, POSSIBLE_WORDS_NUMBER> POSSIBLE_WORDS = std::array < std::string, POSSIBLE_WORDS_NUMBER> {
    "TONUS", "LIEGE", "SABLE", "SAUNA", "RHUME", "DIEUX", "TACHE", "BANJO", "SUCRE", "CAPOT", "FRISE", "EMAIL", "LASER", "ECHEC",
    "GLACON", "FRIMER", "COULIS", "JAUGER", "CRAMPE", "RANCIR", "DEFIER", "MORUES", "CIMENT", "JOUJOU", "DESSIN", "PIMENT",
    "GESTION", "COULEUR", "DOMPTER", "PAPYRUS", "HAUTAIN", "RONFLER", "TACTILE", "SPOLIER", "DOYENNE", "COUVENT", "GLACIER",
    "EPLUCHER", "ORPHELIN", "ENSABLER", "LEGITIME", "CHARMEUR", "RAYONNER", "BATONNET", "GRILLAGE", "ENDOSSER", "ANCIENNE"
};
